### ISSUE TITLE
Misleading error for function call with incorrect argument data.

### ISSUE THREAD

**Issue by dgsmith** [spark/particle-api-js#11]
Using the particle-api-js library in my website I came across a particularly hard to debug issue. When I was trying to send data, I was passing it to the `callFunction` function as an integer but the error I was receiving was saying their was no function found for the name I had used -- very confusing. It wasn't until I used to `toString()` method on the integers that the function calls were completing successfully.

I'm just wondering if there's a way to maybe specify that more directly in the docs or maybe provide a more helpful error message?

Thanks!

**Comment by brycekahle** [comment]
Nice catch. We should probably be coercing values to strings in our API since that the only data type of the argument.

**Comment by dgsmith** [comment]
That'd be great. Cleans up my client code a bit and yeah, I'm always expecting a String in the firmware anyway.

**Comment by brycekahle** [comment]
I've opened an issue on our new `cloud` repo. https://github.com/spark/cloud/issues/1
