### ISSUE TITLE
Replace babel-polyfill with library-contained alternatives

### ISSUE THREAD

**Issue by lourd** [spark/particle-api-js#13]
The way that babel-polyfill is [being used](https://github.com/spark/particle-api-js/blob/master/src/Particle.js#L1) pollutes the runtime environment with feature polyfills that may not be wanted or needed by app developers. For instance, polyfilling Promises when Node 4 and 5 have them natively. 

[This article](https://medium.com/@jcse/clearing-up-the-babel-6-ecosystem-c7678a314bf3#.yn6j8qy6j) is a good explanation on the difference between `babel-polyfill` and `babel-runtime`. 

The recommended solution is to depend on `babel-runtime` and use the [transform-runtime Babel plugin](http://babeljs.io/docs/plugins/transform-runtime/).

**Comment by brycekahle** [comment]
> For instance, polyfilling Promises when Node 4 and 5 have them natively.

A polyfill will not override an existing native implementation. The difference between `babel-polyfill` and `babel-runtime` is whether or not the global namespace is modified to support ES2015.

I can see why an app developer wouldn't want extra code that they don't use. I don't like that we get a full polyfill while only using a few of them. I want to try a couple different ways to get only specific ones we use. Would that alleviate your concerns?

**Comment by lourd** [comment]
Sure. I've seen from a few libraries that want to be explicit specifying individual babel plugins in the .babelrc file instead of using a preset.

**Comment by brycekahle** [comment]
That works for syntax transforms but not runtime dependencies.

**Comment by lourd** [comment]
Right. The solutions I can think of are either tree-shaking in the build process with Rollup or Webpack 2, or switch to explicitly using each polyfill you need.

**Comment by emcniece** [comment]
So I just hit an issue while trying to use particle-api-js in a pre-compiled angular environment:

    Uncaught Error: only one instance of babel-polyfill is allowed

I'm including the script directly in HTML because this is a restrictive node/angular plugin-esque system and I can't get NPM modules through to the front end, which is frustrating to say the least. Is this related to this issue?

**Comment by emcniece** [comment]
@lourd @brycekahle a penny for your thoughts :D

**Comment by lourd** [comment]
Haha 😉 

@brycekahle, any progress made on this? It looks like the methods that may need polyfills are limited to `Object.assign` and `Object.keys`.

**Comment by brycekahle** [comment]
Unfortunately no progress. I'm pretty swamped at the moment so if you have time to put together a PR that polyfills only the necessary features that would be really helpful.

**Comment by emcniece** [comment]
Cool, thanks @brycekahle!

@lourd - this is a bit beyond my knowledge, but I'll try to help out. Here's a first step - it's not working, tests fail on trying to find `babel-runtime`. I'll navigate this maze over the next week or two, but some tips would be greatly appreciated ;)

**Comment by lourd** [comment]
Hey @emcniece, thanks for your initial work. One simple fix is to use explicit userland modules instead of relying on polyfills. For example, use [`object-assign`](https://www.npmjs.com/package/object-assign) and the [`object-keys`](https://www.npmjs.com/package/object-keys) npm packages instead of relying on `Object.keys` and `Object.assign` being implemented in the runtime.

I believe those are the only functions that `babel-polyfill` is actually fulfilling in this package.

**Comment by emcniece** [comment]
I gave your links a shot tonight, and they don't seem to be compatible as they use `require` instead of `import`. I looked around for some other ES6 ObjectAssign polyfills and they all seem to use `require`, which Babel fails on. (`6:1  error  'require' is not defined  no-undef`)

I must be missing something obvious...

**Comment by lourd** [comment]
That sounds like a linter error, not an actual program error.

`require` is built into Node. It's part of what's known as the CommonJS module system. `import` is part of the ES6 module system, as you mentioned. The Babel configuration for this project transpiles the `import` statements into `require` statements. Node does not support ES6 modules natively yet (work is underway, Google '.ejs vs package.json' for some fun reading over the debates happening right now).

So you can use `import` without a problem, i.e. `import assign from 'object-assign-`. The linter is setup to enforce using the new syntax.

**Comment by monkbroc** [comment]
Version 6.0.1 now uses `babel-runtime` instead of `babel-polyfill`. If anybody is still having an issue with the transpiler or sees `only one instance of babel-polyfill is allowed` please comment and I'll reopen this issue.

**Comment by emcniece** [comment]
Confirmed that this works within my project - thank you!
