### ISSUE TITLE
generated docs on github for particle-js don't appear to be working

### ISSUE THREAD

**Issue by dmiddlecamp** [spark/particle-api-js#16]
![screen shot 2016-05-02 at 11 28 31 am](https://cloud.githubusercontent.com/assets/833793/14960198/09b5e82a-1059-11e6-9ccd-a6e22a37d5bb.png)

**Comment by brycekahle** [comment]
Looks good to me? Which part doesn't work?

**Comment by dmiddlecamp** [comment]
I guess I assumed the "$0" "$0." etc shouldn't be there?  It caught me off guard / didn't have an explanation?

**Comment by brycekahle** [comment]
All functions take an anonymous object

**Comment by dmiddlecamp** [comment]
I don't suppose there is a way we can clarify this aspect of the docs?

**Comment by brycekahle** [comment]
Right now it is a limitation of the documentation tool we are using. https://github.com/documentationjs/documentation/blob/master/docs/RECIPES.md#destructuring-parameters
