### ISSUE TITLE
responseTemplate and responseTopic in creation of webhooks

### ISSUE THREAD

**Issue by acasas** [spark/particle-api-js#21]
Hey,

Is there any reason why `responseTemplate` and `responseTopic` are not arguments on the webhook creation call? https://github.com/spark/particle-api-js/blob/master/src/Particle.js#L331

Happy to open up a pull request to add them there - but I wanted to follow up with you guys on this before doing so.

Thanks.

**Comment by brycekahle** [comment]
No reason, a PR would be helpful!

**Comment by acasas** [comment]
Thanks @brycekahle! I hope this one helps https://github.com/spark/particle-api-js/pull/22

**Comment by acasas** [comment]
PR merged.
