### ISSUE TITLE
compileCode Flattens File Hierarchy 

### ISSUE THREAD

**Issue by plasticrake** [spark/particle-api-js#29]
The compileCode method currently doesn't compile projects with a folder hierarchy correctly (#include etc)

The root cause is form-data runs path.basename(filename) which strips the folder from the path.

I see that particle-cli uses a fork of form-data that bypasses this. However particle-api-js doesn't use form-data directly it uses superagent which depends on form-data.

What would be the solution for this? Create a fork of superagent that uses the fork of form-data? Or is there something else planned?

I was hoping that fixing this in particle-api-js would be the first step to fixing particle-dev's build behavior (by migrating from the older SparkJS to particle-api-js)

Summary of which build methods support subfolders:
Web IDE: Yes
particle-cli: Yes
particle-dev: No (uses old SparkJS api)
particle-api-js: No

**Comment by monkbroc** [comment]
This is in progress right now. Stay tuned for a resolution across the entire Particle platform.

**Comment by m-mcgowan** [comment]
@monkbroc - do we know if this needs more work or can be closed?

**Comment by monkbroc** [comment]
This is taken care of with this functionality:
https://github.com/spark/particle-api-js/blob/master/src/Agent.js#L144
