### ISSUE TITLE
Unset 5.3.0-develop.1 as the 'latest' release

### ISSUE THREAD

**Issue by kevireilly** [spark/particle-api-js#37]
There is presently an issue performing `npm install particle-api-js` due to a known [npm bug](https://github.com/npm/npm/issues/10057) which, if I understand it correctly, is due to setting the 'latest' release as 5.3.0-develop.1

As an end-user, you can work around this by doing `npm install particle-api-js@5.3.0`. It is worth noting that the 5.3.0-develop.1 release is generally broken and while I'm not sure it is the appropriate solution, I have forked the repo and made [some fixes](https://github.com/kevireilly/particle-api-js/tree/login).

**Comment by suda** [comment]
Done! Thx Kevin!
