### ISSUE TITLE
Login is not working with version 6.0.0

### ISSUE THREAD

**Issue by levend** [spark/particle-api-js#41]
Hi,

Just tried to test the library, i installed it via npm. With the latest version(6.0.0) I got HTTP 400 for login, and it says:
`HTTP error 400 from https://api.particle.io/oauth/token - Method must be POST with application/x-www-form-urlencoded encoding`
After rolling back to 5.3.1 everything worked fine.

I was not able to install the tests for 6.0.0 version as well.

**Comment by monkbroc** [comment]
Thanks. I'll take a look and release a fix shortly.

**Comment by joshgordon** [comment]
I appear to have the same issue regardless of node version - tried it on 6.3, 4.2 and 0.10 and they all came back with the same error.

**Comment by ScruffR** [comment]
Similar issue here
https://community.particle.io/t/local-server-in-node-js-example/24233/18

**Comment by monkbroc** [comment]
This was an issue with content type for some requests. This is fixed in 6.0.1.
