### ISSUE TITLE
flashDevice() fails in 6.0.3

### ISSUE THREAD

**Issue by chrisb2** [spark/particle-api-js#45]
I have successfully used node.js to execute the following code to load a **tinker.bin** file in versions 5.3.1, 6.0.0, 6.01 and 6.0.2, however it fails in version 6.0.3. Looks like this commit which changed dir handling in Agent.js may be the source of the problem: [Support nested directories when compiling sources](https://github.com/spark/particle-api-js/commit/f9a2426be1da907c6fc6b3a3fdc1d0972e5d107d)

```
/*jslint node: true */
"use strict";

var auth = require('./auth.js');
var Particle = require('particle-api-js');
var particle = new Particle();

particle.login({
    username: auth.username,
    password: auth.password
}).then(
    function(data) {
        console.log('Login success');

        var flashPr = particle.flashDevice({
            deviceId: auth.device,
            files: {
                'tinker.bin': './tinker.bin'
            },
            auth: auth.token
        });

        flashPr.then(
            function(data) {
                console.log('Device flash result:', JSON.stringify(data));
                process.exit();
            },
            function(err) {
                console.log('An error occurred while flashing the device:', err);
            });
    },
    function(err) {
        console.log('Login failed: ', err);
    }
);
```

When I execute it the following is logged:

```
Login success
Device flash result: {"body":{"id":"<device id>","status":"Update started"},"statusCode":200}
```

But shortly after in Particle Console I see a 'spark/flash/status' event with data 'failed'.

To run this you will need an **auth.js** file with your credentials, like:

```
module.exports = {
    username: '<your email>',
    password: '<password>',
    device: '<deviceId>',
    token: '<auth token>'
};
```

This issue was originally raised in the Particle Community forum: [flashDevice() fails in Particle JS API [SOLVED]](https://community.particle.io/t/flashdevice-fails-in-particle-js-api-solved/25410)

**Comment by m-mcgowan** [comment]
Thank you for the bug report and for sleuthing the cause!
