### ISSUE TITLE
Trailing slash on baseUrl

### ISSUE THREAD

**Issue by terminalpixel** [spark/particle-api-js#7]
Hi there,

Just trying to covert my spark stuff over to this new library and ran into 404 errors because the default baseUrl has a trailing slash on it.

Managed to get logged in fine when I passed in the url without the trailing slash.

Cheers,  
Grant

**Comment by mike12345567** [comment]
I have also ran into this issue, updating the `baseUrl: 'https://api.particle.io/'` in `Defaults.js` to remove the trailing slash stopped the 404 errors.

**Comment by brycekahle** [comment]
Thanks for the bug report. I'll check this out.
