### ISSUE TITLE
getEventStream doesn't return any events

### ISSUE THREAD

**Issue by mike12345567** [spark/particle-api-js#8]
I have been attempting to get the list of events for my devices, using the below code.

```
particle.login({ username : "USERNAME", password : "PASSWORD" }).then(function(data) {
  particle.getEventStream({ deviceId: 'mine', auth: data.body.access_token }).then(function(data) {
    console.log("Event: " + data);
  });
});
```

I can see events from my devices by viewing the following web address, so events do appear to be firing correctly.

```
https://api.particle.io/v1/devices/events?access_token=TOKEN
```

However using the `getEventStream` I have not seen any events being logged, I've tried this a few different ways but in no case have I been able to receive events.

**Comment by brycekahle** [comment]
Thanks for the heads up! I'll start investigating.

**Comment by mike12345567** [comment]
Thanks for the quick response!

**Comment by brycekahle** [comment]
@mike12345567 I'm working on this. It appears `superagent` doesn't support streaming responses.

**Comment by mike12345567** [comment]
Thanks for checking this out so quickly, I wondered if it was related to the fact that the events are streamed as I didn't have any issues with the `listDevices` call.

**Comment by brycekahle** [comment]
@mike12345567 Give it a show now. This is how you can use it:
```
particle.login({ username : "USERNAME", password : "PASSWORD" }).then(function(data) {
  particle.getEventStream({ deviceId: 'mine', auth: data.body.access_token }).then(function(stream) {
    stream.on('event', function(e) {
      console.log("Event: " + e);
    });
  });
});

**Comment by mike12345567** [comment]
@brycekahle thanks for looking at this, getting events correctly now!
