### ISSUE TITLE
`getEventStream()` doesn't like `cache-control` header

### ISSUE THREAD

**Issue by morphatic** [spark/particle-api-js#9]
I'm trying to subscribe to my devices' event stream using the JS SDK from an Angular app I'm building with the [Ionic framework](http://ionicframework.com/). I am successfully able to use the SDK to do things like login and retrieve an access token, and get a list of devices. However, when I use the `getEventStream` function, I get the following error:

```
Fetch API Cannot Load
http://api.particle.io/v1/devices/123456/events/spark/status
Request header field cache-control is not allowed by Access-Control-Allow Headers in preflight response.
```

(Of course, 123456 is not my real device ID, but I checked the number and it is correct.) If I use the promise response to catch the error I get:

```
TypeError: Failed to fetch at TypeError (native)
Network error from [url I typed above]
```

If I go into `EventStream.js` and comment out the part where the `cache-control` header is specified (around line 30), i.e. `/*'Cache-Control': 'no-cache',*/` then it seems to work fine. (Actually, I commented this out in `particle.min.js` but in the pre-minified version it's in `EventStream.js`).

Any ideas why this isn't working? I'm testing it using the `ionic serve` process in Google Chrome (Version 48.0.2564.103 (64-bit)) on OSX. I guess it's possible it could be a browser issue, and that the problem will go away when I compile for my mobile device...

If you'd like to check out my code, the part that launches the listener is in [app.js around line 23](https://github.com/morphatic/lapisbubblus/blob/master/www/js/app.js#L23).

NOTE: in the version in my repo, the `cache-control` part is commented out of `particle.min.js`

**Comment by brycekahle** [comment]
It must be adding the `Cache-Control` header to the preflight CORS request. That header is not very crucial for the request, since the response specifies it as well. I will remove it and release a new version first thing tomorrow.

**Comment by morphatic** [comment]
Fantastic. Thanks!! This is an **excellent** product BTW. I'm getting _really_ excited about doing more IoT projects because of this, and since I teach college, I expect I'll be getting a lot of my students involved as well in the upcoming years.

**Comment by brycekahle** [comment]
@morphatic 5.2.2 has your fix.
